# Generated by Django 3.2.7 on 2021-09-07 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=2)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('form_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
