# Generated by Django 3.2.7 on 2021-09-07 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(19)]),
        ),
    ]
